name: '@lazebird/tvconfig_formatter-action'
description: 'Extract domains from tvconfig JSON and generate Clash/OpenClash rule provider YAML or Omnibox configuration file'
author: 'lazebird <lazebird@gmail.com>'
branding:
  color: 'blue'
  icon: 'globe'

inputs:
  config_path:
    description: 'Path to tvconfig JSON configuration file'
    required: true
  output_path:
    description: 'Output path for the generated file'
    required: true
  format:
    description: 'Output format (clash or omnibox)'
    required: false
    default: 'clash'

runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    - name: Generate rule provider
      shell: bash
      run: |
        cd "${{ github.action_path }}"
        npm install
        node src/main.js "${{ github.workspace }}/${{ inputs.config_path }}" -o "${{ github.workspace }}/${{ inputs.output_path }}" -f "${{ inputs.format }}"