name: Test tvconfig2clash-action

on:
  push:
    branches: ["**"]
    paths-ignore:
      - 'output/**'

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'github-actions[bot]' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Generate rule provider from test input
        run: |
          mkdir -p output
          node src/main.js test/config.json -o output/site.yml

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: test-output
          path: output/site.yml

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add output/site.yml
          git commit -m "chore: update output/site.yml via test workflow [skip ci]" || echo "No changes to commit"
          git push